server:
  port: 8082
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
    min-spare-threads: 30

spring:
  application:
    name: cloud-api
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
  #  boot:
  #    admin:
  #      client:
  #        url: http://127.0.0.1:9090
  #  boot:
  #    admin:
  #      # ???????
  #      context-path: /xboot/admin
  #      client:
  #        url: http://127.0.0.1:${server.port}/xboot/admin
  profiles:
    active: dev
  #???
  datasource:
    url: jdbc:mysql://101.132.172.18:3306/dusto_pay?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&netTimeoutForStreamingResults=0&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 1996qwer
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # ????
      auto-commit: true
      connection-test-query: SELECT 1
      # ???????????????????????????????????SQLException? ??:30?
      # ???? connect-time 10 s
      connection-timeout: 9000
      # ????idle???????????????????retired????:10??
      idle-timeout: 600000
      # ???????????????????????????retired????:30?? 1800000ms??????????????60????MySQL wait_timeout 7200s ???# ???????????????????????????retired????:30?? 1800000ms??????????????60????MySQL wait_timeout???show variables like '%timeout%';? -->  ? -->
      max-lifetime: 1800000
      # ?????????????????10???????((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 15
      # ?????
      minimum-idle: 10
      # ?????
      pool-name: DemoHikariCP
mybatis-plus:
  # MyBaits ????????????????????????
  type-aliases-package: com.cloud.dao.entity.CloudUser
  # ????? typeAliasesPackage ?????????????????????????????????? ?
  type-aliases-super-type: java.lang.Object
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # ?????????sql?????????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ???????
    map-underscore-to-camel-case: true
    # ??????????
    cache-enabled: true
    # ???????
    lazy-loading-enabled: true
    # ?????????????????????????????????
    multiple-result-sets-enabled: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100

#ftp
ftp:
  host: 9.111.139.176
  port: 8821
  username: test
  password: test
  filepath: /
